### ISSUE TITLE
Make docs menu item "Adobe RTMP Specification (PDF)" open in a new window. 

### ISSUE THREAD

**Issue by seanbajuice** [veriskope/rtmp-website#1]
Need to add target="_blank" to the Adobe RTMP Specification (PDF) menu item in docs. hrefTargetBlank: "true" isn't working on config.yaml.

**Comment by ultrasaurus** [comment]
We're moving this into markdown instead  -- will be addressed by https://github.com/veriskope/rtmp-website/pull/4
